--- #YAML:1.0
 name: MP3-CreateInlayCard
 abstract: create a CD inlay label for a directory of MP3 files
 version: 0.03
 author:
   - David Precious <davidp@preshweb.co.uk>
 license: perl
 distribution_type: module
 requires:
   File::Recurse: 0
   MP3::Tag: 0
   HTML::Template: 0
   Cwd: 0
   perl: 5.005
 build_requires:
   Test::More: 0
 meta-spec:
   version: 1.3
   url: http://module-build.sourceforge.net/META-spec-v1.3.html
 generated_by: hand
